# Imagen base de Python ligera
FROM python:3.11-slim

# No generar archivos .pyc y salida sin buffer
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Crear carpeta de trabajo
WORKDIR /app

# Copiar e instalar dependencias
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . /app/

# Exponer el puerto donde corre Flask
EXPOSE 5000

# Comando para iniciar la app
CMD ["python", "app.py"]

# Copia todo el contenido de tu proyecto dentro del contenedor
COPY . /app/
